### PR TITLE
updated composer.json

### PR DESCRIPTION
**Pull request by kanariezwart**
widend symfony/yaml requirement to version 3 or 4

### CODE REVIEW

**Comment by kanariezwart** [comment]
Composer symfony yaml requirement could also be version 4+. BC with version 3

**Comment by kanariezwart** [comment]
Can you please have look into this MR, should be a simple merge. Thanks

**Review by ringuedethomas — APPROVED** [review]

**Comment by robertkern** [comment]
@kanariezwart have you confirmed that this library works fine with symfony/yaml 4?

**Comment by kanariezwart** [comment]
@robertkern yes. I ran all tests, all work fine. When you compare https://github.com/symfony/yaml/compare/3.4...4.0 you will see the main difference is added type hinting. 

In the case the php version is lower than 7.1 composer will make sure that version 3.x is installed. See https://github.com/symfony/yaml/compare/3.4...4.0#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780 for details

**Comment by kanariezwart** [comment]
@robertkern 👊

**Pull request merged**
